apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminders-api
  namespace: reminders-main
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: reminders-api
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: reminders-api
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          image: ---CONTAINER_IMAGE_NAME---
          name: clean-architecture-api
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
          resources: {
              requests: { cpu: "250m", memory: "256Mi" },
              limits: { cpu: "2500m", memory: "2560Mi" }
            }
          volumeMounts:
            - mountPath: /app/CleanArchitecture.sqlite
              name: reminders-api-claim0

  hostname: reminders-api
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: aks-pullfrom-dsoapps
