apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.network/reminders-api-default: "true"
    io.kompose.service: api
  name: api
spec:
  containers:
    - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
      image: dsoapps.azurecr.io/dso/reminders-api-main:30
      name: clean-architecture-api
      ports:
        - containerPort: 5001
          hostPort: 5001
          protocol: TCP
      volumeMounts:
        - mountPath: /app/CleanArchitecture.sqlite
          name: api-claim0
  restartPolicy: OnFailure
  imagePullSecrets:
      - name: aks-pullfrom-dsoapps
  volumes:
    - name: api-claim0
      persistentVolumeClaim:
        claimName: api-claim0
